name: monitor_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  nima:
    path: ../../Dependencies/Nima-Flutter/nima
  flare:
    path: ../../Dependencies/Flare-Flutter/flare

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
  - family: Terminus
    fonts:
      - asset: assets/fonts/Terminus.ttf
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
  - family: RobotoMono
    fonts:
      - asset: assets/fonts/RobotoMono-Regular.ttf
      - asset: assets/fonts/RobotoMono-Medium.ttf
  - family: Inconsolata
    fonts:
      - asset: assets/fonts/Inconsolata-Regular.ttf
      - asset: assets/fonts/Inconsolata-Bold.ttf
        weight: 700

  assets:
    - assets/button1.mp3
    - assets/button2.mp3
    - assets/button3.mp3
    - assets/button4.mp3
    - assets/button5.mp3
    # assets/files
    - assets/files/main.dart
    - assets/files/test.dart
    # assets/images
    - assets/nima/NPC1/NPC1.nima
    - assets/nima/NPC1/NPC1.png
    - assets/nima/NPC2/NPC2.nima
    - assets/nima/NPC2/NPC2.png
    - assets/nima/NPC3/NPC3.nima
    - assets/nima/NPC3/NPC3.png
    - assets/nima/NPC4/NPC4.nima
    - assets/nima/NPC4/NPC4.png
    - assets/nima/HotReloadScene/HotReloadScene.nima
    - assets/nima/HotReloadScene/HotReloadScene.png
    - assets/flares/Heart.flr

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
